# Generated by Django 5.0.6 on 2026-05-16 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("predictions", "0002_prediction_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("enthusiast", "Enthusiast"),
                            ("student", "Student / Educator"),
                            ("researcher", "Researcher"),
                        ],
                        default="all",
                        max_length=24,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("predict", "Predict"),
                            ("journal_create", "Journal Create"),
                            ("collection_add", "Collection Add"),
                            ("module_visit", "Module Visit"),
                            ("page_visit", "Page Visit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_count", models.PositiveIntegerField(default=1)),
                ("reward_xp", models.PositiveIntegerField(default=25)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("apod", "APOD"),
                            ("mars_photo", "Mars Photo"),
                            ("exoplanet", "Exoplanet"),
                            ("neo", "NEO"),
                            ("epic", "EPIC"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ref_id", models.CharField(max_length=128)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="portal.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("-added_at",),
                "unique_together": {("collection", "kind", "ref_id")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body_md", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("inspired", "Inspired"),
                            ("curious", "Curious"),
                            ("analytical", "Analytical"),
                            ("celebratory", "Celebratory"),
                        ],
                        default="curious",
                        max_length=24,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="predictions.prediction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-pinned", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="portal_jour_user_id_02665d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MissionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(default=django.utils.timezone.localdate)),
                ("count", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_rows",
                        to="portal.mission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-day", "-updated_at"),
                "unique_together": {("user", "mission", "day")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mission", "Mission"),
                            ("achievement", "Achievement"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="portal_noti_user_id_af50dc_idx",
                    ),
                    models.Index(
                        fields=["user", "read_at"],
                        name="portal_noti_user_id_d5ad53_idx",
                    ),
                ],
            },
        ),
    ]
